// <auto-generated />
using System;
using EFDiyetUygulamasi.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFDiyetUygulamasi.DAL.Migrations
{
    [DbContext(typeof(UygulamaDbContext))]
    [Migration("20231206132508_Uc")]
    partial class Uc
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Besin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Kalori")
                        .HasColumnType("int");

                    b.Property<decimal>("Karbonhidrat")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<int>("KategoriId")
                        .HasColumnType("int");

                    b.Property<decimal>("Protein")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.Property<decimal>("Yag")
                        .HasPrecision(5, 1)
                        .HasColumnType("decimal(5,1)");

                    b.HasKey("Id");

                    b.HasIndex("KategoriId");

                    b.ToTable("Besinler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Terbiyeli Köfte",
                            Kalori = 231,
                            Karbonhidrat = 5.7m,
                            KategoriId = 1,
                            Protein = 20.5m,
                            Yag = 15.3m
                        },
                        new
                        {
                            Id = 2,
                            Ad = "İzmir Köfte",
                            Kalori = 343,
                            Karbonhidrat = 3.7m,
                            KategoriId = 1,
                            Protein = 18.2m,
                            Yag = 28.4m
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Fırın Tavuk",
                            Kalori = 275,
                            Karbonhidrat = 1.8m,
                            KategoriId = 1,
                            Protein = 24.8m,
                            Yag = 17.2m
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Kuzu Tandır",
                            Kalori = 420,
                            Karbonhidrat = 0.9m,
                            KategoriId = 1,
                            Protein = 29.5m,
                            Yag = 34.8m
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Köfte Izgara",
                            Kalori = 310,
                            Karbonhidrat = 2.4m,
                            KategoriId = 1,
                            Protein = 22.1m,
                            Yag = 23.7m
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Beyti",
                            Kalori = 489,
                            Karbonhidrat = 26.8m,
                            KategoriId = 1,
                            Protein = 24.8m,
                            Yag = 23.2m
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Patlıcan Kebabı",
                            Kalori = 265,
                            Karbonhidrat = 12.7m,
                            KategoriId = 1,
                            Protein = 9.4m,
                            Yag = 20.1m
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Hünkar Beğendi",
                            Kalori = 380,
                            Karbonhidrat = 8.3m,
                            KategoriId = 1,
                            Protein = 22.5m,
                            Yag = 28.6m
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Cızlak Kebap",
                            Kalori = 310,
                            Karbonhidrat = 3.2m,
                            KategoriId = 1,
                            Protein = 17.8m,
                            Yag = 24.5m
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Ciğer Sote",
                            Kalori = 280,
                            Karbonhidrat = 3.8m,
                            KategoriId = 1,
                            Protein = 18.6m,
                            Yag = 21.4m
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Tavuklu Pilav",
                            Kalori = 320,
                            Karbonhidrat = 28.1m,
                            KategoriId = 1,
                            Protein = 20.2m,
                            Yag = 12.5m
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Fırın Mantarlı Tavuk",
                            Kalori = 290,
                            Karbonhidrat = 3.7m,
                            KategoriId = 1,
                            Protein = 26.8m,
                            Yag = 19.3m
                        },
                        new
                        {
                            Id = 13,
                            Ad = "Dana Kavurma",
                            Kalori = 360,
                            Karbonhidrat = 0.9m,
                            KategoriId = 1,
                            Protein = 22.3m,
                            Yag = 29.8m
                        },
                        new
                        {
                            Id = 14,
                            Ad = "Zeytinyağlı Yaprak Sarma",
                            Kalori = 180,
                            Karbonhidrat = 22.8m,
                            KategoriId = 1,
                            Protein = 3.5m,
                            Yag = 9.2m
                        },
                        new
                        {
                            Id = 15,
                            Ad = "Kuzu İncik",
                            Kalori = 450,
                            Karbonhidrat = 1.2m,
                            KategoriId = 1,
                            Protein = 30.7m,
                            Yag = 36.2m
                        },
                        new
                        {
                            Id = 16,
                            Ad = "Balık Tava",
                            Kalori = 260,
                            Karbonhidrat = 0.6m,
                            KategoriId = 1,
                            Protein = 24.1m,
                            Yag = 17.8m
                        },
                        new
                        {
                            Id = 17,
                            Ad = "Kağıt Kebabı",
                            Kalori = 310,
                            Karbonhidrat = 2.4m,
                            KategoriId = 1,
                            Protein = 22.5m,
                            Yag = 23.7m
                        },
                        new
                        {
                            Id = 18,
                            Ad = "Tavuk Kapama",
                            Kalori = 280,
                            Karbonhidrat = 3.8m,
                            KategoriId = 1,
                            Protein = 19.3m,
                            Yag = 20.1m
                        },
                        new
                        {
                            Id = 19,
                            Ad = "Ali Nazik Kebabı",
                            Kalori = 340,
                            Karbonhidrat = 6.3m,
                            KategoriId = 1,
                            Protein = 21.7m,
                            Yag = 25.2m
                        },
                        new
                        {
                            Id = 20,
                            Ad = "Kuzu Güveç",
                            Kalori = 390,
                            Karbonhidrat = 0.9m,
                            KategoriId = 1,
                            Protein = 28.2m,
                            Yag = 31.6m
                        },
                        new
                        {
                            Id = 21,
                            Ad = "İskender",
                            Kalori = 480,
                            Karbonhidrat = 18.4m,
                            KategoriId = 1,
                            Protein = 26.7m,
                            Yag = 33.2m
                        },
                        new
                        {
                            Id = 22,
                            Ad = "Fırın Tavuk But",
                            Kalori = 310,
                            Karbonhidrat = 0.8m,
                            KategoriId = 1,
                            Protein = 24.5m,
                            Yag = 21.2m
                        },
                        new
                        {
                            Id = 23,
                            Ad = "Tavuklu Karnabahar",
                            Kalori = 240,
                            Karbonhidrat = 5.7m,
                            KategoriId = 1,
                            Protein = 18.2m,
                            Yag = 16.9m
                        },
                        new
                        {
                            Id = 24,
                            Ad = "Balıklı Pilav",
                            Kalori = 360,
                            Karbonhidrat = 27.9m,
                            KategoriId = 1,
                            Protein = 25.6m,
                            Yag = 14.8m
                        },
                        new
                        {
                            Id = 25,
                            Ad = "Hamsili Ekmek",
                            Kalori = 280,
                            Karbonhidrat = 7.1m,
                            KategoriId = 1,
                            Protein = 20.3m,
                            Yag = 18.9m
                        },
                        new
                        {
                            Id = 26,
                            Ad = "Fırın Mantarlı Tavuk",
                            Kalori = 290,
                            Karbonhidrat = 3.7m,
                            KategoriId = 1,
                            Protein = 26.8m,
                            Yag = 19.3m
                        },
                        new
                        {
                            Id = 27,
                            Ad = "Peynirli Kuzu Kuyma",
                            Kalori = 420,
                            Karbonhidrat = 1.9m,
                            KategoriId = 1,
                            Protein = 30.5m,
                            Yag = 34.1m
                        },
                        new
                        {
                            Id = 28,
                            Ad = "Cevizli Kuzu Güveç",
                            Kalori = 380,
                            Karbonhidrat = 5.3m,
                            KategoriId = 1,
                            Protein = 25.2m,
                            Yag = 29.7m
                        },
                        new
                        {
                            Id = 29,
                            Ad = "Fırın Tavuk Kanat",
                            Kalori = 270,
                            Karbonhidrat = 0.6m,
                            KategoriId = 1,
                            Protein = 23.4m,
                            Yag = 18.1m
                        },
                        new
                        {
                            Id = 30,
                            Ad = "Yogurtlu Tavuk Şiş",
                            Kalori = 320,
                            Karbonhidrat = 3.2m,
                            KategoriId = 1,
                            Protein = 22.8m,
                            Yag = 24.5m
                        },
                        new
                        {
                            Id = 31,
                            Ad = "Fırın Karnabahar Kızartması",
                            Kalori = 180,
                            Karbonhidrat = 15.8m,
                            KategoriId = 2,
                            Protein = 6.7m,
                            Yag = 12.4m
                        },
                        new
                        {
                            Id = 32,
                            Ad = "Patlıcanlı Kıymalı Güveç",
                            Kalori = 250,
                            Karbonhidrat = 7.9m,
                            KategoriId = 2,
                            Protein = 14.3m,
                            Yag = 18.6m
                        },
                        new
                        {
                            Id = 33,
                            Ad = "Kuzu Kapama",
                            Kalori = 320,
                            Karbonhidrat = 2.8m,
                            KategoriId = 2,
                            Protein = 22.5m,
                            Yag = 25.1m
                        },
                        new
                        {
                            Id = 34,
                            Ad = "Zeytinyağlı Pırasa",
                            Kalori = 150,
                            Karbonhidrat = 11.8m,
                            KategoriId = 2,
                            Protein = 4.6m,
                            Yag = 10.2m
                        },
                        new
                        {
                            Id = 35,
                            Ad = "Taze Fasulye Türlü",
                            Kalori = 200,
                            Karbonhidrat = 13.5m,
                            KategoriId = 2,
                            Protein = 9.8m,
                            Yag = 12.7m
                        },
                        new
                        {
                            Id = 36,
                            Ad = "Kabak Karnabahar Graten",
                            Kalori = 280,
                            Karbonhidrat = 16.8m,
                            KategoriId = 2,
                            Protein = 13.6m,
                            Yag = 19.3m
                        },
                        new
                        {
                            Id = 37,
                            Ad = "Sebzeli Kıymalı Börek",
                            Kalori = 320,
                            Karbonhidrat = 7.2m,
                            KategoriId = 2,
                            Protein = 18.7m,
                            Yag = 24.5m
                        },
                        new
                        {
                            Id = 38,
                            Ad = "Zeytinyağlı Enginar",
                            Kalori = 180,
                            Karbonhidrat = 11.5m,
                            KategoriId = 2,
                            Protein = 4.2m,
                            Yag = 13.8m
                        },
                        new
                        {
                            Id = 39,
                            Ad = "Kırmızı Mercimek Koftesi",
                            Kalori = 240,
                            Karbonhidrat = 6.5m,
                            KategoriId = 2,
                            Protein = 12.3m,
                            Yag = 18.9m
                        },
                        new
                        {
                            Id = 40,
                            Ad = "Karnabahar Köftesi",
                            Kalori = 210,
                            Karbonhidrat = 16.7m,
                            KategoriId = 2,
                            Protein = 8.5m,
                            Yag = 14.2m
                        },
                        new
                        {
                            Id = 41,
                            Ad = "Quinoa Salatası",
                            Kalori = 180,
                            Karbonhidrat = 19.8m,
                            KategoriId = 3,
                            Protein = 6.5m,
                            Yag = 9.2m
                        },
                        new
                        {
                            Id = 42,
                            Ad = "Cevizli Kabak Tarator",
                            Kalori = 220,
                            Karbonhidrat = 11.3m,
                            KategoriId = 3,
                            Protein = 5.8m,
                            Yag = 17.1m
                        },
                        new
                        {
                            Id = 43,
                            Ad = "Karnabahar Kuskusu",
                            Kalori = 250,
                            Karbonhidrat = 28.4m,
                            KategoriId = 3,
                            Protein = 7.3m,
                            Yag = 12.9m
                        },
                        new
                        {
                            Id = 44,
                            Ad = "Bulgur Pilavı",
                            Kalori = 290,
                            Karbonhidrat = 61.2m,
                            KategoriId = 3,
                            Protein = 6.7m,
                            Yag = 1.5m
                        },
                        new
                        {
                            Id = 45,
                            Ad = "İncirli Armut Pilavı",
                            Kalori = 310,
                            Karbonhidrat = 66.5m,
                            KategoriId = 3,
                            Protein = 8.2m,
                            Yag = 4.6m
                        },
                        new
                        {
                            Id = 46,
                            Ad = "Yulaf Ezmesi",
                            Kalori = 180,
                            Karbonhidrat = 33.5m,
                            KategoriId = 3,
                            Protein = 5.4m,
                            Yag = 3.2m
                        },
                        new
                        {
                            Id = 47,
                            Ad = "Pirinç Pilavı",
                            Kalori = 320,
                            Karbonhidrat = 69.4m,
                            KategoriId = 3,
                            Protein = 6.9m,
                            Yag = 1.8m
                        },
                        new
                        {
                            Id = 48,
                            Ad = "Fasulye Pilavı",
                            Kalori = 250,
                            Karbonhidrat = 47.2m,
                            KategoriId = 3,
                            Protein = 7.8m,
                            Yag = 3.5m
                        },
                        new
                        {
                            Id = 49,
                            Ad = "Beyaz Nohut Pilavı",
                            Kalori = 280,
                            Karbonhidrat = 53.8m,
                            KategoriId = 3,
                            Protein = 10.1m,
                            Yag = 4.7m
                        },
                        new
                        {
                            Id = 50,
                            Ad = "Kabaklı Bulgur Pilavı",
                            Kalori = 210,
                            Karbonhidrat = 43.7m,
                            KategoriId = 3,
                            Protein = 5.9m,
                            Yag = 2.1m
                        },
                        new
                        {
                            Id = 51,
                            Ad = "Zeytinyağlı Yaprak Sarma",
                            Kalori = 180,
                            Karbonhidrat = 15.2m,
                            KategoriId = 4,
                            Protein = 3.5m,
                            Yag = 12.6m
                        },
                        new
                        {
                            Id = 52,
                            Ad = "Zeytinyağlı Kabak Dolması",
                            Kalori = 150,
                            Karbonhidrat = 12.4m,
                            KategoriId = 4,
                            Protein = 2.8m,
                            Yag = 10.3m
                        },
                        new
                        {
                            Id = 53,
                            Ad = "Zeytinyağlı Pırasa",
                            Kalori = 120,
                            Karbonhidrat = 9.7m,
                            KategoriId = 4,
                            Protein = 2.4m,
                            Yag = 8.1m
                        },
                        new
                        {
                            Id = 54,
                            Ad = "Zeytinyağlı Taze Fasulye",
                            Kalori = 140,
                            Karbonhidrat = 11.5m,
                            KategoriId = 4,
                            Protein = 3.1m,
                            Yag = 8.8m
                        },
                        new
                        {
                            Id = 55,
                            Ad = "Zeytinyağlı Enginar",
                            Kalori = 200,
                            Karbonhidrat = 14.7m,
                            KategoriId = 4,
                            Protein = 4.6m,
                            Yag = 15.4m
                        },
                        new
                        {
                            Id = 56,
                            Ad = "Zeytinyağlı Karnabahar",
                            Kalori = 160,
                            Karbonhidrat = 12.9m,
                            KategoriId = 4,
                            Protein = 3.2m,
                            Yag = 11.5m
                        },
                        new
                        {
                            Id = 57,
                            Ad = "Zeytinyağlı Bamya",
                            Kalori = 130,
                            Karbonhidrat = 10.7m,
                            KategoriId = 4,
                            Protein = 2.9m,
                            Yag = 8.6m
                        },
                        new
                        {
                            Id = 58,
                            Ad = "Zeytinyağlı Ispanak",
                            Kalori = 110,
                            Karbonhidrat = 9.4m,
                            KategoriId = 4,
                            Protein = 2.1m,
                            Yag = 7.2m
                        },
                        new
                        {
                            Id = 59,
                            Ad = "Zeytinyağlı Pırasa Yemeği",
                            Kalori = 140,
                            Karbonhidrat = 11.8m,
                            KategoriId = 4,
                            Protein = 3.3m,
                            Yag = 9.2m
                        },
                        new
                        {
                            Id = 60,
                            Ad = "Zeytinyağlı Taze Fasulye Pilaki",
                            Kalori = 150,
                            Karbonhidrat = 12.5m,
                            KategoriId = 4,
                            Protein = 3.7m,
                            Yag = 9.8m
                        },
                        new
                        {
                            Id = 71,
                            Ad = "Mercimek Çorbası",
                            Kalori = 150,
                            Karbonhidrat = 21.8m,
                            KategoriId = 5,
                            Protein = 9.5m,
                            Yag = 3.2m
                        },
                        new
                        {
                            Id = 72,
                            Ad = "Tarator Çorbası",
                            Kalori = 120,
                            Karbonhidrat = 12.6m,
                            KategoriId = 5,
                            Protein = 7.8m,
                            Yag = 5.1m
                        },
                        new
                        {
                            Id = 73,
                            Ad = "Domates Çorbası",
                            Kalori = 110,
                            Karbonhidrat = 18.5m,
                            KategoriId = 5,
                            Protein = 4.2m,
                            Yag = 2.8m
                        },
                        new
                        {
                            Id = 74,
                            Ad = "Tavuklu Şehriye Çorbası",
                            Kalori = 180,
                            Karbonhidrat = 23.7m,
                            KategoriId = 5,
                            Protein = 12.3m,
                            Yag = 4.6m
                        },
                        new
                        {
                            Id = 75,
                            Ad = "Ezogelin Çorbası",
                            Kalori = 160,
                            Karbonhidrat = 24.2m,
                            KategoriId = 5,
                            Protein = 8.9m,
                            Yag = 3.5m
                        },
                        new
                        {
                            Id = 76,
                            Ad = "Yoğurtlu Çorba",
                            Kalori = 140,
                            Karbonhidrat = 15.9m,
                            KategoriId = 5,
                            Protein = 7.4m,
                            Yag = 6.8m
                        },
                        new
                        {
                            Id = 77,
                            Ad = "Kremalı Mantar Çorbası",
                            Kalori = 220,
                            Karbonhidrat = 9.7m,
                            KategoriId = 5,
                            Protein = 5.6m,
                            Yag = 18.3m
                        },
                        new
                        {
                            Id = 78,
                            Ad = "Kabak Çorbası",
                            Kalori = 130,
                            Karbonhidrat = 14.8m,
                            KategoriId = 5,
                            Protein = 3.7m,
                            Yag = 7.2m
                        },
                        new
                        {
                            Id = 79,
                            Ad = "Kırmızı Mercimek Çorbası",
                            Kalori = 160,
                            Karbonhidrat = 25.4m,
                            KategoriId = 5,
                            Protein = 9.8m,
                            Yag = 2.6m
                        },
                        new
                        {
                            Id = 80,
                            Ad = "İrmik Helvası",
                            Kalori = 528,
                            Karbonhidrat = 63.3m,
                            KategoriId = 6,
                            Protein = 7.6m,
                            Yag = 29.8m
                        },
                        new
                        {
                            Id = 81,
                            Ad = "Sütlaç",
                            Kalori = 347,
                            Karbonhidrat = 67.2m,
                            KategoriId = 6,
                            Protein = 8.2m,
                            Yag = 7.2m
                        },
                        new
                        {
                            Id = 82,
                            Ad = "Baklava",
                            Kalori = 450,
                            Karbonhidrat = 40.2m,
                            KategoriId = 6,
                            Protein = 7.5m,
                            Yag = 29.5m
                        },
                        new
                        {
                            Id = 83,
                            Ad = "Kazandibi",
                            Kalori = 280,
                            Karbonhidrat = 35.2m,
                            KategoriId = 6,
                            Protein = 5.8m,
                            Yag = 12.6m
                        },
                        new
                        {
                            Id = 84,
                            Ad = "Revani",
                            Kalori = 315,
                            Karbonhidrat = 38.1m,
                            KategoriId = 6,
                            Protein = 6.2m,
                            Yag = 15.8m
                        },
                        new
                        {
                            Id = 85,
                            Ad = "Dondurma",
                            Kalori = 207,
                            Karbonhidrat = 22.6m,
                            KategoriId = 6,
                            Protein = 5.4m,
                            Yag = 11.2m
                        },
                        new
                        {
                            Id = 86,
                            Ad = "Domates Salatası",
                            Kalori = 127,
                            Karbonhidrat = 11.6m,
                            KategoriId = 7,
                            Protein = 2.5m,
                            Yag = 8.4m
                        },
                        new
                        {
                            Id = 87,
                            Ad = "Cacık",
                            Kalori = 75,
                            Karbonhidrat = 3.9m,
                            KategoriId = 7,
                            Protein = 3.2m,
                            Yag = 5.6m
                        },
                        new
                        {
                            Id = 88,
                            Ad = "Roka Salatası",
                            Kalori = 64,
                            Karbonhidrat = 2.9m,
                            KategoriId = 7,
                            Protein = 3.9m,
                            Yag = 4.7m
                        },
                        new
                        {
                            Id = 89,
                            Ad = "Ceasar Salatası",
                            Kalori = 184,
                            Karbonhidrat = 3.2m,
                            KategoriId = 7,
                            Protein = 4.8m,
                            Yag = 16.7m
                        },
                        new
                        {
                            Id = 90,
                            Ad = "Mevsim Salatası",
                            Kalori = 95,
                            Karbonhidrat = 7.6m,
                            KategoriId = 7,
                            Protein = 3.1m,
                            Yag = 6.4m
                        },
                        new
                        {
                            Id = 92,
                            Ad = "Kayısı",
                            Kalori = 63,
                            Karbonhidrat = 15.3m,
                            KategoriId = 8,
                            Protein = 1.0m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 93,
                            Ad = "Muz",
                            Kalori = 96,
                            Karbonhidrat = 25.0m,
                            KategoriId = 8,
                            Protein = 1.3m,
                            Yag = 0.3m
                        },
                        new
                        {
                            Id = 94,
                            Ad = "Kiraz",
                            Kalori = 63,
                            Karbonhidrat = 16.0m,
                            KategoriId = 8,
                            Protein = 1.1m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 95,
                            Ad = "Üzüm",
                            Kalori = 69,
                            Karbonhidrat = 17.5m,
                            KategoriId = 8,
                            Protein = 0.7m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 96,
                            Ad = "Kavun",
                            Kalori = 73,
                            Karbonhidrat = 18.0m,
                            KategoriId = 8,
                            Protein = 0.9m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 97,
                            Ad = "Karpuz",
                            Kalori = 30,
                            Karbonhidrat = 8.0m,
                            KategoriId = 8,
                            Protein = 0.6m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 98,
                            Ad = "Portakal",
                            Kalori = 43,
                            Karbonhidrat = 8.3m,
                            KategoriId = 8,
                            Protein = 1.0m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 99,
                            Ad = "Mandalina",
                            Kalori = 70,
                            Karbonhidrat = 13.5m,
                            KategoriId = 8,
                            Protein = 0.8m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 100,
                            Ad = "Malta eriği",
                            Kalori = 38,
                            Karbonhidrat = 9.6m,
                            KategoriId = 8,
                            Protein = 0.9m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 101,
                            Ad = "Elma",
                            Kalori = 52,
                            Karbonhidrat = 14.0m,
                            KategoriId = 8,
                            Protein = 0.3m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 102,
                            Ad = "Toz Şeker",
                            Kalori = 76,
                            Karbonhidrat = 20.0m,
                            KategoriId = 9,
                            Protein = 0.0m,
                            Yag = 0.0m
                        },
                        new
                        {
                            Id = 103,
                            Ad = "Peynir (Kaşar)",
                            Kalori = 121,
                            Karbonhidrat = 1.0m,
                            KategoriId = 9,
                            Protein = 6.0m,
                            Yag = 10.0m
                        },
                        new
                        {
                            Id = 104,
                            Ad = "Peynir(Beyaz)",
                            Kalori = 87,
                            Karbonhidrat = 1.0m,
                            KategoriId = 9,
                            Protein = 7.0m,
                            Yag = 6.0m
                        },
                        new
                        {
                            Id = 105,
                            Ad = "Reçel",
                            Kalori = 96,
                            Karbonhidrat = 25.0m,
                            KategoriId = 9,
                            Protein = 0.3m,
                            Yag = 0.1m
                        },
                        new
                        {
                            Id = 106,
                            Ad = "Yağ(Margarin)",
                            Kalori = 221,
                            Karbonhidrat = 0.0m,
                            KategoriId = 9,
                            Protein = 0.3m,
                            Yag = 24.0m
                        },
                        new
                        {
                            Id = 107,
                            Ad = "Yumurta",
                            Kalori = 80,
                            Karbonhidrat = 1.0m,
                            KategoriId = 9,
                            Protein = 6.0m,
                            Yag = 5.0m
                        },
                        new
                        {
                            Id = 108,
                            Ad = "Zeytin(Yeşil)",
                            Kalori = 43,
                            Karbonhidrat = 0.0m,
                            KategoriId = 9,
                            Protein = 0.5m,
                            Yag = 4.0m
                        },
                        new
                        {
                            Id = 109,
                            Ad = "Zeytin(Siyah)",
                            Kalori = 62,
                            Karbonhidrat = 1.0m,
                            KategoriId = 9,
                            Protein = 0.5m,
                            Yag = 6.0m
                        },
                        new
                        {
                            Id = 110,
                            Ad = "Ekmek",
                            Kalori = 276,
                            Karbonhidrat = 56.0m,
                            KategoriId = 9,
                            Protein = 9.0m,
                            Yag = 1.0m
                        },
                        new
                        {
                            Id = 111,
                            Ad = "İnek Sütü",
                            Kalori = 61,
                            Karbonhidrat = 5.0m,
                            KategoriId = 10,
                            Protein = 3.0m,
                            Yag = 3.0m
                        },
                        new
                        {
                            Id = 112,
                            Ad = "Yoğurt",
                            Kalori = 63,
                            Karbonhidrat = 4.0m,
                            KategoriId = 10,
                            Protein = 4.0m,
                            Yag = 3.0m
                        },
                        new
                        {
                            Id = 115,
                            Ad = "Kola",
                            Kalori = 140,
                            Karbonhidrat = 39.0m,
                            KategoriId = 11,
                            Protein = 0.0m,
                            Yag = 0.0m
                        },
                        new
                        {
                            Id = 116,
                            Ad = "Portakal Suyu",
                            Kalori = 110,
                            Karbonhidrat = 26.0m,
                            KategoriId = 11,
                            Protein = 2.0m,
                            Yag = 0.5m
                        },
                        new
                        {
                            Id = 117,
                            Ad = "Limonata",
                            Kalori = 120,
                            Karbonhidrat = 30.0m,
                            KategoriId = 11,
                            Protein = 0.5m,
                            Yag = 0.0m
                        },
                        new
                        {
                            Id = 118,
                            Ad = "Gazoz",
                            Kalori = 90,
                            Karbonhidrat = 24.0m,
                            KategoriId = 11,
                            Protein = 0.0m,
                            Yag = 0.0m
                        },
                        new
                        {
                            Id = 119,
                            Ad = "Meyve Smoothie",
                            Kalori = 200,
                            Karbonhidrat = 45.0m,
                            KategoriId = 11,
                            Protein = 2.5m,
                            Yag = 1.0m
                        },
                        new
                        {
                            Id = 120,
                            Ad = "Türk Kahvesi",
                            Kalori = 5,
                            Karbonhidrat = 0.0m,
                            KategoriId = 12,
                            Protein = 0.5m,
                            Yag = 0.2m
                        },
                        new
                        {
                            Id = 121,
                            Ad = "Siyah Çay",
                            Kalori = 2,
                            Karbonhidrat = 0.5m,
                            KategoriId = 12,
                            Protein = 0.1m,
                            Yag = 0.0m
                        },
                        new
                        {
                            Id = 122,
                            Ad = "Yeşil Çay",
                            Kalori = 0,
                            Karbonhidrat = 0.0m,
                            KategoriId = 12,
                            Protein = 0.0m,
                            Yag = 0.0m
                        },
                        new
                        {
                            Id = 123,
                            Ad = "Nane Limon Çayı",
                            Kalori = 4,
                            Karbonhidrat = 0.8m,
                            KategoriId = 12,
                            Protein = 0.1m,
                            Yag = 0.0m
                        },
                        new
                        {
                            Id = 124,
                            Ad = "Salep",
                            Kalori = 150,
                            Karbonhidrat = 30.0m,
                            KategoriId = 12,
                            Protein = 1.5m,
                            Yag = 2.0m
                        });
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Kategori", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kategoriler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Et Yemekleri"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Etli Sebze Yemekleri"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Tahıllı Yemekler"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Zeytin Yağlı Sebze Yemekleri"
                        },
                        new
                        {
                            Id = 5,
                            Ad = "Çorbalar"
                        },
                        new
                        {
                            Id = 6,
                            Ad = "Tatlılar"
                        },
                        new
                        {
                            Id = 7,
                            Ad = "Salatalar"
                        },
                        new
                        {
                            Id = 8,
                            Ad = "Meyvelar"
                        },
                        new
                        {
                            Id = 9,
                            Ad = "Kahvaltılıklar"
                        },
                        new
                        {
                            Id = 10,
                            Ad = "Süt ve Süt Ürünleri"
                        },
                        new
                        {
                            Id = 11,
                            Ad = "Soğuk İçecekler"
                        },
                        new
                        {
                            Id = 12,
                            Ad = "Sıcak İçecekler"
                        });
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Kullanici", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sifre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.KullaniciProfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Boy")
                        .HasColumnType("int");

                    b.Property<int>("Cinsiyet")
                        .HasColumnType("int");

                    b.Property<decimal>("Kilo")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yas")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId")
                        .IsUnique();

                    b.ToTable("KullaniciProfiller");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Ogun", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ogunler");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Ad = "Kahvaltı"
                        },
                        new
                        {
                            Id = 2,
                            Ad = "Ara Öğünler"
                        },
                        new
                        {
                            Id = 3,
                            Ad = "Öğle Yemeği"
                        },
                        new
                        {
                            Id = 4,
                            Ad = "Akşam Yemeği"
                        });
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.OgunBilgisi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BesinId")
                        .HasColumnType("int");

                    b.Property<int>("KullaniciId")
                        .HasColumnType("int");

                    b.Property<int>("OgunId")
                        .HasColumnType("int");

                    b.Property<int>("Porsiyon")
                        .HasColumnType("int");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BesinId");

                    b.HasIndex("KullaniciId");

                    b.HasIndex("OgunId");

                    b.ToTable("OgunBilgiler");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Besin", b =>
                {
                    b.HasOne("EFDiyetUygulamasi.DAL.Entities.Kategori", "Kategori")
                        .WithMany("Besinler")
                        .HasForeignKey("KategoriId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategori");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.KullaniciProfil", b =>
                {
                    b.HasOne("EFDiyetUygulamasi.DAL.Entities.Kullanici", "Kullanici")
                        .WithOne("KullaniciProfil")
                        .HasForeignKey("EFDiyetUygulamasi.DAL.Entities.KullaniciProfil", "KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.OgunBilgisi", b =>
                {
                    b.HasOne("EFDiyetUygulamasi.DAL.Entities.Besin", "Besin")
                        .WithMany("OgunBilgiler")
                        .HasForeignKey("BesinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDiyetUygulamasi.DAL.Entities.Kullanici", "Kullanici")
                        .WithMany("OgunBilgiler")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFDiyetUygulamasi.DAL.Entities.Ogun", "Ogun")
                        .WithMany("OgunBilgiler")
                        .HasForeignKey("OgunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Besin");

                    b.Navigation("Kullanici");

                    b.Navigation("Ogun");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Besin", b =>
                {
                    b.Navigation("OgunBilgiler");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Kategori", b =>
                {
                    b.Navigation("Besinler");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Kullanici", b =>
                {
                    b.Navigation("KullaniciProfil")
                        .IsRequired();

                    b.Navigation("OgunBilgiler");
                });

            modelBuilder.Entity("EFDiyetUygulamasi.DAL.Entities.Ogun", b =>
                {
                    b.Navigation("OgunBilgiler");
                });
#pragma warning restore 612, 618
        }
    }
}
